from typing import Protocol
from uuid import UUID

from regulaflow.application.records import BatchRecord, RunRecord


class BatchStore(Protocol):
    def ping(self) -> None: ...

    def get_by_identifier(self, identifier: str) -> BatchRecord | None: ...

    def get(self, batch_id: UUID) -> BatchRecord | None: ...

    def add(self, batch: BatchRecord) -> None: ...

    def save_run(self, batch_id: UUID, run: RunRecord) -> BatchRecord: ...

    def list_batches(self) -> tuple[BatchRecord, ...]: ...
